CoreZeroAdministrator:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin-staff

CoreZeroApi:
    resource: "@CoreZeroBundle/Controller/"
    type:     annotation
    prefix:   /
