CoreZeroAdministrator:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin-staff

fos_user_security_login:
    pattern: /ingresar
    defaults: { _controller: CoreZeroBundle:Security:login }
    requirements:
        _method: GET|POST

fos_user_security_check:
    pattern: /comprobar_ingreso
    defaults: { _controller: CoreZeroBundle:Security:check }

fos_user_security_logout:
    pattern: /salir
    defaults: { _controller: CoreZeroBundle:Security:logout }
    requirements:
        _method: GET|POST

CoreZeroApi:
    resource: "@CoreZeroBundle/Controller/"
    type:     annotation
    prefix:   /
